<%@ Page Title="Alpha Professional Tools® : Privacy" Language="C#" MasterPageFile="~/MasterPages/Home.master" AutoEventWireup="true" CodeFile="Privacy.aspx.cs" Inherits="pages_Privacy" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <asp:PlaceHolder runat="server" ID="metaTags" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Body" runat="server">
    <div class="page-intro">
        <ol id="Breadcrumb" class="breadcrumb" runat="server">
            </ol>
    </div>
     <section class="main-container" style="margin-top: 0px;">
           <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="title">
                                <h3 runat="server">Privacy Policy</h3>
                            </span></div>
                        <div class="panel-body">
                          <div id="landing_page">
                              <div class="text_block">
                             <ul>
                                    <li><a href="#General">General</a></li>
                                  <li><a href="#Acceptance Of Terms; Changes To This Privacy Policy">Acceptance Of Terms; Changes To This Privacy Policy</a></li>
                                    <li><a href="#Why Alpha® Collects Personal Information">Why Alpha® Collects Personal Information</a></li>
                                    <li><a href="#How Alpha® Collects Personal Information">How Alpha® Collects Personal Information</a></li>
                                    <li><a href="#Use of Information">Use of Information</a></li>
                                    <li><a href="#representations">Disclosure Of Information</a></li>
                                    <li><a href="#Disclosure Of Information">Cross Reference Information</a></li>
                                    <li><a href="#Your Choices/Your Privacy Rights">Your Choices/Your Privacy Rights</a></li>
                                    <li><a href="#Maintenance and Processing of Information in the U.S. and Other Countries">Maintenance and Processing of Information in the U.S. and Other Countries</a></li>
                                    <li><a href="#Access To Your Personal Information">Access To Your Personal Information</a></li>
<li><a href="#Security">Security</a></li>
<li><a href="#Children's Privacy">Children's Privacy</a></li>
<li><a href="#Third-Party Websites">Third-Party Websites</a></li>
<li><a href="#California Privacy Rights">California Privacy Rights</a></li>
<li><a href="#TGoverning Law; Jurisdiction">Governing Law; Jurisdiction</a></li>
<li><a href="#Contact Us">Contact Us</a></li>
                              </ul></div>
                                <hr>
                        <div class="page_text"><h3><a name="General"></a>General</h3> <p>This Privacy Policy  applies  to personal information that Alpha<sup>&reg;</sup> collects about you on or through <a href="http://www.alpha-tools.com">www.alpha-tools.com</a>, or one of Alpha® other websites, applications, publications, forums or other  services from which you are accessing this Privacy Policy (collectively, the &ldquo;<strong>Alpha<sup>&reg;</sup> Property</strong>&rdquo;). </p>
      <p>&ldquo;<strong>Personal information</strong>&rdquo; includes information that can be used to  uniquely identify you, such as your name, postal address, zip or postal code,  e-mail address, telephone number, date of birth, social security number, credit  card or other payment information, demographic information, or details on items  and services purchased.  This Privacy  Policy describes how Alpha<sup>&reg;</sup> collects such information, how Alpha<sup>&reg;</sup> uses it and  to whom and under what circumstances Alpha<sup>&reg;</sup> may disclose it.</p>
      <p>This Privacy Policy  does not apply to the collection, disclosure or use of personal information  of past or present employees or consultants of the Company for employment,  engagement or benefits administration purposes, all of which is governed by  other policies of the Company designed for those respective purposes.</p>
      <p>If you have any  questions regarding this Privacy Policy or the Alpha<sup>&reg;</sup> information collection and  use practices, please contact Alpha<sup>&reg;</sup> using the information in the &quot;Contact  Us&quot; section below.</p>

                            <!-- end div class="page_text" -->
            <div class="top"><a href="#top">return to top &and;</a></div>
            <hr><div class="page_text"><h3><a name="Acceptance Of Terms; Changes To This Privacy Policy"></a>Acceptance Of Terms; Changes To This Privacy Policy</h3><p>By using the Alpha<sup>&reg;</sup> Property, you acknowledge  that you have reviewed the terms of this Privacy Policy and agree that Alpha<sup>&reg;</sup> may  collect, use and transfer your personal information in accordance therewith. If  you do not agree with these terms, you may choose not to use the Alpha<sup>&reg;</sup> Property,  and please do not provide any personal information through the Alpha<sup>&reg;</sup> Property.  </p>
Alpha<sup>&reg;</sup> may change  this Privacy Policy from time to time and the amended policy will be posted to  the Alpha<sup>&reg;</sup> Property. Alpha<sup>&reg;</sup> reserves the right to update, change, amend or  modify this Policy at any time and from time to time without prior notice. When  Alpha<sup>&reg;</sup> posts changes to this Privacy Policy, Alpha<sup>&reg;</sup> will revise the &ldquo;Last  Updated&rdquo; date at the top of the Privacy Policy. Your continued use of the Alpha<sup>&reg;</sup> Property after any changes or revisions to this Privacy Policy become effective  shall indicate your agreement with the terms of such revised and then-current Privacy Policy. </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text"><h3><a name="Why Alpha® Collects Personal Information"></a>Why Alpha<sup>&reg;</sup> Collects Personal Information</h3>
                            <p>Alpha® collects and uses personal information for many purposes, including but  not limited to, billing; product and service fulfillment; to better understand the Alpha<sup>&reg;</sup> customer needs; to  provide a better website, products and services; and to communicate with  customers and potential customers regarding the Alpha<sup>&reg;</sup> products and services and third party products  and services.</p>
                            </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text"><h3><a name="How Alpha® Collects Personal Information"></a>How Alpha<sup>&reg;</sup> Collects Personal Information</h3><p><em><u>Information You Provide To Alpha®</u></em><em>.  </em></p>
                              <p>Alpha® (or the Alpha<sup>&reg;</sup> service  providers) collects information from you when you: (1) create an account with Alpha<sup>&reg;</sup> (your &ldquo;<strong>Account</strong>&rdquo;), or otherwise sign  up for a service or feature; (2) purchase products or services from Alpha<sup>&reg;</sup> on the  Alpha<sup>&reg;</sup> Property; (3) complete a survey; (4) participate in a sweepstakes,  contest or other promotion; (5) communicate with Alpha<sup>&reg;</sup> via third-party social  media sites; (6) apply for a job with Alpha<sup>&reg;</sup>; or (7) contact Alpha<sup>&reg;</sup>, or  otherwise communicate with Alpha<sup>&reg;</sup> or provide information to Alpha<sup>&reg;</sup>. </p>
                              <p>Alpha<sup>&reg;</sup> may combine  your (and others&rsquo;) information that Alpha® has collected from you (or others)  with information Alpha<sup>&reg;</sup> may receive from other sources, such as third-party  social media platforms (e.g., when you choose to log in to the Alpha<sup>&reg;</sup> Property through  a third-party social media platform, subject to your actions and settings  thereon), address update services and co-promotion partners. By accessing any Alpha<sup>&reg;</sup> Property, you signify your consent to the above collection of your personal  information. </p>
                              <p>If you do not want Alpha<sup>&reg;</sup> to collect your personal information, please do not provide it to Alpha<sup>&reg;</sup>. </p>
                     
                              <p><em><u>Alpha<sup>&reg;</sup> Property Information &amp; Other Information  Collected Automatically</u></em><em>.  </em></p>
                              <p>As part of the  standard operation of the Alpha<sup>&reg;</sup> Property, certain information is collected  automatically or passively from or about you in connection with your visit to  the Alpha<sup>&reg;</sup> Property. The Alpha<sup>&reg;</sup> servers may automatically gather some of the Alpha<sup>&reg;</sup> Property usage information (as defined below), or Alpha<sup>&reg;</sup> (or the Alpha<sup>&reg;</sup> service  providers) may use cookies and other tracking technologies to collect and track  such information. </p>
                              <p>&ldquo;<strong>Alpha<sup>&reg;</sup> Property usage information</strong>&rdquo; includes, but is not limited to:  (i) your browser type, device type, carrier (if applicable), device address,  operating system, operating system address, IP address and the domain name from  which you accessed Alpha<sup>&reg;</sup> Property; (ii) information about your region,  continent, country, city, zip code, time zone, and general location; and (iii)  information about your browsing activities on and through Alpha<sup>&reg;</sup> Property (also  known as &ldquo;Click Stream&rdquo; data), such as (a) the date and time you visit the  Alpha<sup>&reg;</sup> Property, (b) the areas or pages of the Alpha<sup>&reg;</sup> Property that you visit,  (c) the amount of time you spend viewing the Alpha<sup>&reg;</sup> Property or specific areas  of the Alpha<sup>&reg;</sup> Property, (d) the number of times you return to the Alpha<sup>&reg;</sup> Property or a specific area of the Alpha<sup>&reg;</sup> Property, (e) the web sites or pages  you visited prior to visiting the Alpha<sup>&reg;</sup> Property, (f) the websites or pages  you visit after you leave the Alpha<sup>&reg;</sup> Property; (g) searches you have performed  on the Alpha<sup>&reg;</sup> Property and on other websites that led you to the Alpha<sup>&reg;</sup> Property; (h) social plug-ins with which you have interacted on the Alpha<sup>&reg;</sup> Property;  and (j) other similar Alpha<sup>&reg;</sup> Property usage data.</p>
                              <p>Alpha<sup>&reg;</sup> considers the  Alpha<sup>&reg;</sup> Property usage information, on its own, to be non-personal in nature,  unless required otherwise by applicable law. However, Alpha<sup>&reg;</sup> may combine Alpha<sup>&reg;</sup> Property usage information about you with personal information about you, and Alpha<sup>&reg;</sup> would consider the combined information to be &ldquo;personally identifiable&rdquo; or personal  information for the purposes of this Privacy Policy.</p>
                              
                              <p><em><u>Browser Do-Not Track Signals</u></em><em>. </em></p>
                              <p>Some web browsers and  devices permit you to broadcast a preference that you not be &ldquo;tracked&rdquo; online.  At this time, Alpha<sup>&reg;</sup> does not modify your experience based on whether such a  signal is broadcast. To learn more about browser tracking signals and &ldquo;Do Not  Track,&rdquo; please visit <a href="http://allaboutdnt.org">http://allaboutdnt.org</a>.</p>
                         
                              <p><em><u>Cookies and Other  Tracking Technologies</u></em><em>.  </em></p>
                              <p>Alpha<sup>&reg;</sup> and its service providers may use cookies, pixel tags,  web beacons, Adobe Flash Technology and other similar technologies, which allow  Alpha<sup>&reg;</sup> to, among other things, optimize the Alpha<sup>&reg;</sup> Property and to understand  traffic and usage patterns. Additionally, if the settings on your  location-aware devise allow Alpha<sup>&reg;</sup> to receive geo-location data or information,  Alpha<sup>&reg;</sup> may collect that information automatically.</p>
                              <p>A cookie is a small data file that is sent to your web  browser and placed on your computer or device when you access a website.  Cookies allow parties (including Alpha<sup>&reg;</sup>, its service providers and other) to: (i)  track your activities on the Alpha<sup>&reg;</sup> Property, (ii) track clicks, purchases and  conversion; (iii) recognize your computer or device so that you are able to  save your preference and stay logged in to the Alpha<sup>&reg;</sup> Property without having  to re-enter your Account credentials; (iv) deliver customized content, messages  and advertising to you; (v) preserve the contents of your shopping cart; (vi) and  otherwise enhance and personalize your experience on the Alpha<sup>&reg;</sup> Property. If  you do not want information collected through the use of cookies, most devices  allow you to decline the use of cookies. Alpha<sup>&reg;</sup> recommends that you leave  cookies turned on because if you elect not to allow them, you may not be able  to use or to enjoy all of the services and features of the Alpha<sup>&reg;</sup> Property.</p>
                              <p>Alpha<sup>&reg;</sup> may use Flash cookies and other similar  technologies, which allow a website to store certain information locally on an  individual&rsquo;s computer or device and then access and use that information to  enhance and facilitate certain Alpha<sup>&reg;</sup> Property experiences, processes and  functionality. Flash cookies are different from other cookies and may not be  removed in the same manner. More information about both kinds of cookies is  available at <a href="http://www.allaboutcookies.org">www.allaboutcookies.org</a>. </p>
                              <p>Alpha<sup>&reg;</sup> may also use web beacons (also known as &ldquo;clear  GIFs&rdquo; or &ldquo;pixel tags&rdquo;) for similar purposes as cookies. These beacons are  typically one-pixel images that are embedded in the Alpha<sup>&reg;</sup> Property or in a  communication, such as an e-mail message. These technologies help Alpha<sup>&reg;</sup> to  verify when a certain page of Alpha<sup>&reg;</sup> Property is viewed, when a message is  opened and when links or other content in a message are clicked or viewed. </p>
                              <p>Alpha<sup>&reg;</sup> may use third party web analytics services, such  as Google Analytics and Adobe services, to help Alpha<sup>&reg;</sup> track and analyze the  use of the Alpha<sup>&reg;</sup> Property and to measure the effectiveness of the Alpha<sup>&reg;</sup> advertising,  site content, and communications. These service providers&rsquo; tools, including,  for example, cookies, tags and web beacons, help Alpha<sup>&reg;</sup> to gain this  understanding. </p>
                              <p><em><u>Advertising on the Alpha<sup>&reg;</sup> Property and  Other Websites</u></em><em>. </em></p>
<p>Alpha<sup>&reg;</sup> also works with service providers  and partner with advertising companies that use cookies, web beacons and other  tools to collect information about your visits to and behavior on the Alpha<sup>&reg;</sup> Property and other websites, and then use that information to deliver targeted  advertisements to you across the Internet. The information collected and used  in this manner is generally, on its own, anonymous and not personally  identifiable. </p>
                              <div>
                                <div> </div>
                              </div>
                            </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text">
                              <h3><a name="Use of Information"></a>Use Of Information</h3>
                              <p>Alpha<sup>&reg;</sup> may use the  information it collects from and about you (including both personal information  and Alpha<sup>&reg;</sup> Property usage information) for a variety of purposes, including but  not limited to the following: (i) to fulfill your requests for products and  services and to keep you informed about your orders; (ii) to provide you with  targeted offers and advertising on and at the Alpha<sup>&reg;</sup> Property; (iii) subject to  your communications preferences and, where required by applicable law, subject  to your consent, to contact you (via postal mail, e-mail and the like) with  promotional materials about Alpha<sup>&reg;</sup>, its products, services and events, as well  as about select partners; (iv) to contact you when necessary or appropriate; where  appropriate, for market research and to review and improve Alpha<sup>&reg;</sup> products and  services, customer service, online and offline operations and overall customer  experience; (v) to protect the security or integrity of the Alpha<sup>&reg;</sup> Property and  the Alpha<sup>&reg;</sup> business; or (vi) as otherwise permitted by law or permitted with your  permission.</p>
                              <p>If you provide Alpha<sup>&reg;</sup> with information about another person (as described above in the &ldquo;Information  You Provide To Alpha<sup>&reg;</sup>&rdquo; section), where permitted applicable by law, Alpha<sup>&reg;</sup> uses  that information to fulfill your requests and treat such information in  accordance with this Privacy Policy.</p>
Alpha<sup>&reg;</sup> (and its service  providers) also analyze and use Alpha<sup>&reg;</sup> Property usage information and  information collected through cookies, web beacons and other tracking  technologies, alone and in combination with personal information, to assess the  behavior of Alpha<sup>&reg;</sup> Property users, to measure the interest in and use of the Alpha®  Property and communications, and to customize the Alpha<sup>&reg;</sup> Property and the Alpha<sup>&reg;</sup> communications  with you. Alpha<sup>&reg;</sup> does this both on an individual basis and in the aggregate.</div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text">
                              <h3><a name="Disclosure Of Information"></a>Disclosure Of Information</h3>
                              <p>Alpha<sup>&reg;</sup> may disclose  information it collects (including personal information and Alpha<sup>&reg;</sup> Property usage  information) in the following ways, to the extent permitted by law:</p>
                              <ul>
                                <li><span dir="ltr"> </span>to the Alpha<sup>&reg;</sup> service  providers and suppliers who collect or use such information for Alpha<sup>&reg;</sup> or on its  behalf (such as website or database hosting companies, address list hosting  companies, e-mail service providers, analytics companies, distribution  companies, fulfillment companies, and other similar entities that help Alpha<sup>&reg;</sup> to  operate the Alpha<sup>&reg;</sup> Property and/or provide functionality, content and  services);</li>
                              </ul>
                              <p><span dir="ltr"> </span>to third party  marketers so that they can directly inform you about  products or services which may be of interest to you;</p>
                              <ul>
                                <li><span dir="ltr"> </span>as necessary,  if Alpha<sup>&reg;</sup> believe that there has been a violation of a Alpha<sup>&reg;</sup> Property&rsquo;s Terms  of Use or any other policy of Alpha<sup>&reg;</sup> Property, or if Alpha<sup>&reg;</sup> have reason to  believe that its rights or property, or the rights or property of any third  party, may be or have been harmed;</li>
                              </ul>
                              <p><span dir="ltr"> </span>to respond to  subpoenas or other judicial processes, or to provide information as requested  by law; </p>
                              <ul>
                                <li><span dir="ltr"> </span>in the event  that Alpha<sup>&reg;</sup> or substantially all of its assets are acquired by one or more  third parties as a result of an acquisition, merger, sale, consolidation,  bankruptcy, liquidation or other similar corporate reorganization, where your  information may be one of the transferred assets; and</li>
                              </ul>
                              <p><span dir="ltr"> </span>as otherwise  permitted by law or permitted with your permission.</p>
Content and  information that you submit on or through Facebook, Twitter, LinkedIn and other  third-party platforms may appear on the Alpha<sup>&reg;</sup> Property through feeds from and  other interfaces with those platforms. Alpha<sup>&reg;</sup> is not responsible for the  information, content and/or privacy practices of any such third-party  platforms.</div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text"><h3><a name="Your Choices/Your Privacy Rights"></a>Your Choices/Your Privacy Rights</h3>
                            <p>If you would like to  opt out of receiving direct mail from Alpha<sup>&reg;</sup>, please contact Alpha<sup>&reg;</sup> at <a href="mailto:policy@alpha-tools.com">policy@alpha-tools.com</a>.  Please understand that if you opt out of receiving promotional correspondence  from Alpha<sup>&reg;</sup>, Alpha<sup>&reg;</sup> may still contact you in connection with your Account,  relationship, activities, transactions and communications with Alpha<sup>&reg;</sup>.</p>
                              <p>If you would like to  opt out of receiving promotional e-mails from Alpha<sup>&reg;</sup>, please follow the  unsubscribe instructions located in each such e-mail or contact Alpha<sup>&reg;</sup> at <a href="mailto:policy@alpha-tools.com">policy@alpha-tools.com</a>.  Please understand that if you opt out of  receiving promotional correspondence from Alpha<sup>&reg;</sup>, Alpha<sup>&reg;</sup> may still contact you  in connection with your Account, relationship, activities, transactions and  communications with Alpha<sup>&reg;</sup>. </p>
If you would prefer  that Alpha<sup>&reg;</sup> not share your personal information with third-party marketers,  please contact Alpha<sup>&reg;</sup> at <a href="mailto:policy@alpha-tools.com">policy@alpha-tools.com</a>. Please understand that if you  do request that Alpha<sup>&reg;</sup> stop sharing your personal information with third  parties for their direct marketing purposes, such request will only apply as of  the date of your request, and Alpha<sup>&reg;</sup> will not be responsible for any  communications that you may receive from third parties that received your personal  information prior to that request. In these cases, please opt out from or  contact the third party directly.</div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
                            <hr><div class="page_text"><h3><a name="Maintenance and Processing of Information in the U.S. and Other Countries"></a>Maintenance and Processing of Information in the U.S. and Other Countries</h3><p>Your personal and  other information may be stored, transferred and processed in and to the United  States and other countries and territories. By providing personal information  to Alpha<sup>&reg;</sup>, you consent to the collection, maintenance, processing and transfer  of such information in and to the United States and other countries and  territories, pursuant to the laws of the United States or such other  jurisdictions, which may provide lesser privacy protection than the laws of  other countries, and you acknowledge that your information may thus be subject  to U.S. laws and accessible to the U.S. government, courts, law enforcement and  regulatory agencies.</p>
                            </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text">
               <h3><a name="Access To Your Personal Information"></a>Access To Your Personal Information</h3>
               <p>You may access any personal  information you provide to Alpha<sup>&reg;</sup>, correct or modify any such personal  information, or direct Alpha<sup>&reg;</sup> to delete or make no further use of your personal  information. You can access or make certain adjustments to your Account  directly through your online Account. </p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>               
             <hr><div class="page_text">
               <h3><a name="Security"></a>Security</h3>
               <p>Alpha<sup>&reg;</sup> has implemented  measures in an effort to safeguard the personal information in the Alpha<sup>&reg;</sup> custody  and control. Such measures include, for example, limiting access to personal  information only to employees and authorized service providers who need to know  such information for the purposes described in this Privacy Policy, as well as  other administrative, technical and physical safeguards. Additionally, the Alpha<sup>&reg;</sup> service providers are not authorized to use or disclose your personal  information for any purpose other than providing the services to Alpha<sup>&reg;</sup> or on its  behalf, or as otherwise may be required by applicable law. While Alpha<sup>&reg;</sup> endeavors  to always protect its systems, due to the inherent nature of the Internet as an  open global communications vehicle and other risk factors, Alpha<sup>&reg;</sup> cannot  guarantee that any information, during transmission or while stored on its  systems, will be absolutely safe from intrusion by others, such as hackers. </p>
To provide you with  increased security, access to certain personal information stored in your Account  is protected with your username and password. You are responsible for  maintaining the confidentiality of your Account credentials, and Alpha<sup>&reg;</sup> strongly  recommends that you do not disclose your account username or password to  anyone. Alpha<sup>&reg;</sup> will never ask you for your password in any unsolicited  communication. Please notify Alpha<sup>&reg;</sup> immediately of any unauthorized use of your  Account credentials or any other suspected breach of security.</div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text">
               <h3><a name="Children's Privacy"></a>Children's Privacy</h3>
               <p>The Alpha<sup>&reg;</sup> Property is not directed to children under the age of  thirteen (13). If you are under thirteen (13), do not provide your personal  information on or to the Alpha<sup>&reg;</sup> Property. Alpha<sup>&reg;</sup> does not knowingly collect on  the Alpha<sup>&reg;</sup> Property any personal information from children under thirteen (13).  Users outside of the United States who are below the age of eighteen (18) (or  the age of the majority in the applicable jurisdiction) should not use the Alpha<sup>&reg;</sup> Property without authorization from a parent or legal guardian.</p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text">
               <h3><a name="Third-Party Websites"></a>Third-Party Websites</h3>
               <p>The Alpha<sup>&reg;</sup> Property may contain links (which may take the form of  hyperlinks, widgets, clickable logos, plug-ins, images or banners) to websites  and services operated by entities other than Alpha<sup>&reg;</sup>. This Privacy Policy does  not apply to such websites or services, so Alpha<sup>&reg;</sup> recommends that you review  their posted privacy policies so that you understand the relevant information  collection, use and disclosure practices.</p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text">
               <h3><a name="California Privacy Rights"></a>California Privacy Rights</h3>
               <p>California Civil Code Section 1798.83 permits the Alpha<sup>&reg;</sup> individual customers  who are California residents to request and obtain from Alpha<sup>&reg;</sup> once a year,  free of charge, information about the personal identification information (if  any) Alpha<sup>&reg;</sup> disclosed to third parties for direct marketing purposes in the  preceding calendar year. If applicable, this information would include a list  of the categories of personal identification information that was shared and  the names and addresses of all third parties with which Alpha<sup>&reg;</sup> shared  information in the immediately preceding calendar year.  If you are a California resident and would  like to make such a request, please submit your request in writing as indicated  in the &ldquo;Contact Us&rdquo; section below. </p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text"><h3><a name="Governing Law; Jurisdictione"></a>Governing Law; Jurisdiction</h3><p>This Privacy Policy will be governed by and construed in accordance with  the internal laws of New Jersey without regard to conflicts of laws principles.  By using the Alpha<sup>&reg;</sup> Property, you hereby agree that any and all disputes  regarding these Terms will be subject to the courts located in Bergen County,  New Jersey, and you hereby agree to submit to the personal and exclusive  personal jurisdiction of the aforementioned courts,</p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>
             <hr><div class="page_text">
               <h3><a name="Contact Us"></a>Contact Us</h3>
               <p>If you have any questions about this Privacy Policy, please contact Alpha<sup>&reg;</sup> via e-mail at <a href="mailto:policy@alpha-tools.com">policy@alpha-tools.com</a></p>
             </div><!-- end div class="page_text" --><div class="top"><a href="#top">return to top &and;</a></div>

             
             
                            <span class="title">
                            <h3 id="PageH3" runat="server"></h3>
                            </span>
                        </div>
                        

                    </div>
                </div>
            </div>
    </section>
</asp:Content>


