//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliations
    {
        public System.DateTime DatePosted { get; set; }
        public string AffiliateName { get; set; }
        public string AffiliateLogo { get; set; }
        public string AffiliateLink { get; set; }
        public bool CurrentYN { get; set; }
    }
}
