//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AlphatoolEntities : DbContext
    {
        public AlphatoolEntities()
            : base("name=AlphatoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CMSPageRef> CMSPageRef { get; set; }
        public DbSet<Collection> Collection { get; set; }
        public DbSet<CollectionDupInfo> CollectionDupInfo { get; set; }
        public DbSet<CollectionEmail> CollectionEmail { get; set; }
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<HomeBanners> HomeBanners { get; set; }
        public DbSet<HomeProducts> HomeProducts { get; set; }
        public DbSet<LinksType> LinksType { get; set; }
        public DbSet<MAdvisoryType> MAdvisoryType { get; set; }
        public DbSet<MApplication> MApplication { get; set; }
        public DbSet<MCAProp65> MCAProp65 { get; set; }
        public DbSet<MContact> MContact { get; set; }
        public DbSet<MFlyer> MFlyer { get; set; }
        public DbSet<MIndustry> MIndustry { get; set; }
        public DbSet<MLibrary> MLibrary { get; set; }
        public DbSet<MMaintenanceCard> MMaintenanceCard { get; set; }
        public DbSet<MManual> MManual { get; set; }
        public DbSet<MMaterial> MMaterial { get; set; }
        public DbSet<MMsds> MMsds { get; set; }
        public DbSet<MNetTitle> MNetTitle { get; set; }
        public DbSet<MOtherRef1> MOtherRef1 { get; set; }
        public DbSet<MOtherRef2> MOtherRef2 { get; set; }
        public DbSet<MOtherRef3> MOtherRef3 { get; set; }
        public DbSet<MOtherReference> MOtherReference { get; set; }
        public DbSet<MPageGroup> MPageGroup { get; set; }
        public DbSet<MPageSection> MPageSection { get; set; }
        public DbSet<MPartsList> MPartsList { get; set; }
        public DbSet<MPartUsage> MPartUsage { get; set; }
        public DbSet<MPPCIndustry> MPPCIndustry { get; set; }
        public DbSet<MPPCIndustrySectionGroupPages> MPPCIndustrySectionGroupPages { get; set; }
        public DbSet<MPPCIndustrySectionGroupSpareParts> MPPCIndustrySectionGroupSpareParts { get; set; }
        public DbSet<MProcess> MProcess { get; set; }
        public DbSet<MRegion> MRegion { get; set; }
        public DbSet<MTechNote> MTechNote { get; set; }
        public DbSet<MTerritory> MTerritory { get; set; }
        public DbSet<MWebGroup> MWebGroup { get; set; }
        public DbSet<MWebSection> MWebSection { get; set; }
        public DbSet<MWebTitle> MWebTitle { get; set; }
        public DbSet<NetPriceInfo> NetPriceInfo { get; set; }
        public DbSet<PartsInfo> PartsInfo { get; set; }
        public DbSet<PartsPage> PartsPage { get; set; }
        public DbSet<PressRelease> PressRelease { get; set; }
        public DbSet<ProductAdvisory> ProductAdvisory { get; set; }
        public DbSet<ProductFields> ProductFields { get; set; }
        public DbSet<ProductFieldsOLD> ProductFieldsOLD { get; set; }
        public DbSet<ProductFieldsPending> ProductFieldsPending { get; set; }
        public DbSet<ProductInfo> ProductInfo { get; set; }
        public DbSet<ProductPage> ProductPage { get; set; }
        public DbSet<ProductRegistration> ProductRegistration { get; set; }
        public DbSet<ProductRelatedText> ProductRelatedText { get; set; }
        public DbSet<ProductRelatedTextNew> ProductRelatedTextNew { get; set; }
        public DbSet<ProductText> ProductText { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TNTechNote> TNTechNote { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<Webfields> Webfields { get; set; }
        public DbSet<Webfields2> Webfields2 { get; set; }
        public DbSet<WebPartNo> WebPartNo { get; set; }
        public DbSet<AboutUs> AboutUs { get; set; }
        public DbSet<Affiliations> Affiliations { get; set; }
        public DbSet<Catalogs> Catalogs { get; set; }
        public DbSet<DealerInfo> DealerInfo { get; set; }
        public DbSet<EducationalMaterial> EducationalMaterial { get; set; }
        public DbSet<EmailSignup> EmailSignup { get; set; }
        public DbSet<Employment> Employment { get; set; }
        public DbSet<EventCalendar> EventCalendar { get; set; }
        public DbSet<Links> Links { get; set; }
        public DbSet<MDealerWebSiteType> MDealerWebSiteType { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<MetalProducts> MetalProducts { get; set; }
        public DbSet<MProductRegModel> MProductRegModel { get; set; }
        public DbSet<NewProducts> NewProducts { get; set; }
        public DbSet<PartsWebfields> PartsWebfields { get; set; }
        public DbSet<Policies> Policies { get; set; }
        public DbSet<ProductBulletins> ProductBulletins { get; set; }
        public DbSet<ProductBullets> ProductBullets { get; set; }
        public DbSet<ProductPage_Snippets> ProductPage_Snippets { get; set; }
        public DbSet<ProductVideo> ProductVideo { get; set; }
        public DbSet<RequestADealerInfo> RequestADealerInfo { get; set; }
        public DbSet<Shop_Description> Shop_Description { get; set; }
        public DbSet<Shopatron> Shopatron { get; set; }
        public DbSet<ShopIntlCatData> ShopIntlCatData { get; set; }
        public DbSet<ShopIntlCatDataTP> ShopIntlCatDataTP { get; set; }
        public DbSet<ShopIntlProductData> ShopIntlProductData { get; set; }
        public DbSet<ShopIntlProductDataTP> ShopIntlProductDataTP { get; set; }
        public DbSet<ShopIntlSpecUpload> ShopIntlSpecUpload { get; set; }
        public DbSet<ShopWebFields> ShopWebFields { get; set; }
        public DbSet<TechnicalLibrary> TechnicalLibrary { get; set; }
        public DbSet<WhatIsNew> WhatIsNew { get; set; }
        public DbSet<ONYX_AlphaWebOnyx_dbo_ProductText> ONYX_AlphaWebOnyx_dbo_ProductText { get; set; }
        public DbSet<ONYX_AlphaWebOnyx_dbo_ProductText1> ONYX_AlphaWebOnyx_dbo_ProductText1 { get; set; }
        public DbSet<VIEWProductPageNoProductText> VIEWProductPageNoProductText { get; set; }
        public DbSet<VIEWProductPageProductText> VIEWProductPageProductText { get; set; }
        public DbSet<VIEWWebfieldsIndustry> VIEWWebfieldsIndustry { get; set; }
        public DbSet<VIEWWebfieldsMaterial> VIEWWebfieldsMaterial { get; set; }
        public DbSet<VIEWWebfieldsUsageProcessApplication> VIEWWebfieldsUsageProcessApplication { get; set; }
    
        public virtual int EventCalendarUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EventCalendarUpdate");
        }
    
        public virtual ObjectResult<GetRecordCountsForAllTables_Result> GetRecordCountsForAllTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecordCountsForAllTables_Result>("GetRecordCountsForAllTables");
        }
    
        public virtual int Shop1_Drop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Shop1_Drop");
        }
    
        public virtual int Shop2_Fetch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Shop2_Fetch");
        }
    
        public virtual int Shop3_Data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Shop3_Data");
        }
    
        public virtual int Shop3_PartData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Shop3_PartData");
        }
    
        public virtual ObjectResult<Shop4_Extract_Result> Shop4_Extract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Shop4_Extract_Result>("Shop4_Extract");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spDeleteDupCollection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteDupCollection");
        }
    
        public virtual ObjectResult<spTNChart_Result> spTNChart(Nullable<decimal> pPCode)
        {
            var pPCodeParameter = pPCode.HasValue ?
                new ObjectParameter("PPCode", pPCode) :
                new ObjectParameter("PPCode", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTNChart_Result>("spTNChart", pPCodeParameter);
        }
    
        public virtual int spTNChartTemp(Nullable<decimal> pPCode)
        {
            var pPCodeParameter = pPCode.HasValue ?
                new ObjectParameter("PPCode", pPCode) :
                new ObjectParameter("PPCode", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTNChartTemp", pPCodeParameter);
        }
    
        public virtual ObjectResult<spTNChartTemp4_Result> spTNChartTemp4(Nullable<decimal> pPCode)
        {
            var pPCodeParameter = pPCode.HasValue ?
                new ObjectParameter("PPCode", pPCode) :
                new ObjectParameter("PPCode", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTNChartTemp4_Result>("spTNChartTemp4", pPCodeParameter);
        }
    
        public virtual ObjectResult<spVideoTemplate_Result> spVideoTemplate(Nullable<decimal> pPCode)
        {
            var pPCodeParameter = pPCode.HasValue ?
                new ObjectParameter("PPCode", pPCode) :
                new ObjectParameter("PPCode", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spVideoTemplate_Result>("spVideoTemplate", pPCodeParameter);
        }
    
        public virtual int spWebMatInd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spWebMatInd");
        }
    }
}
