//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSPageRef
    {
        public string CMSPage { get; set; }
        public Nullable<int> WebsiteID { get; set; }
        public string CMSContent { get; set; }
        public string CMSTitle { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string EditorName { get; set; }
        public Nullable<int> AffiliateID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CMSCategoryId { get; set; }
        public int CMSVersion { get; set; }
        public string Live { get; set; }
        public string PageURL { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTag { get; set; }
        public Nullable<short> IsFooter { get; set; }
        public Nullable<short> IsLeftMenu { get; set; }
        public Nullable<int> LeftMenuOrder { get; set; }
        public Nullable<int> FooterMenuOrder { get; set; }
    }
}
