//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionEmail
    {
        public decimal SelectedBtnIn { get; set; }
        public string EmailForward { get; set; }
        public string CollectionDescription { get; set; }
        public string Question1 { get; set; }
        public string Question2 { get; set; }
    }
}
