//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerInfo
    {
        public decimal DealerID { get; set; }
        public string Location { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> DealerLogoID { get; set; }
        public string SLXAccountID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PricingInfo { get; set; }
    }
}
