//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalMaterial
    {
        public string PartNo { get; set; }
        public decimal ProductPageCode { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<System.DateTime> DateListed { get; set; }
        public string EdProductDescription { get; set; }
        public string EdProductTitle { get; set; }
        public string EdProductSummary { get; set; }
        public string EdProductPhoto { get; set; }
        public string EdProductPDF { get; set; }
        public bool CurrentYN { get; set; }
    
        public virtual ProductPage ProductPage { get; set; }
    }
}
