//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCalendar
    {
        public System.DateTime DatePosted { get; set; }
        public Nullable<System.DateTime> DateListed { get; set; }
        public string EventTitle { get; set; }
        public string EventBlurb { get; set; }
        public string EventDetailPDF { get; set; }
        public string EventLogo { get; set; }
        public string EventLink { get; set; }
        public bool CurrentYN { get; set; }
    }
}
