//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCarousel
    {
        public decimal HomeCarouselNo { get; set; }
        public string HCarName { get; set; }
        public string HCarImage { get; set; }
        public string HCarLink { get; set; }
        public bool CurrentYN { get; set; }
    }
}
