//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeProducts
    {
        public decimal HomeProductsNo { get; set; }
        public string HPName { get; set; }
        public string HPImage { get; set; }
        public string HPLink { get; set; }
        public bool CurrentYN { get; set; }
        public Nullable<decimal> Sort { get; set; }
    }
}
