//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeBanners
    {
        public decimal HomeBannerNo { get; set; }
        public string HBName { get; set; }
        public string HBImage { get; set; }
        public string HBLink { get; set; }
        public bool CurrentYN { get; set; }
        public Nullable<decimal> Sort { get; set; }
    }
}
