//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinksType
    {
        public LinksType()
        {
            this.Links = new HashSet<Links>();
        }
    
        public decimal LinkType { get; set; }
        public string LinkTypeDescription { get; set; }
    
        public virtual ICollection<Links> Links { get; set; }
    }
}
