//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public decimal LinkType { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string LinkName { get; set; }
        public string LinkLogo { get; set; }
        public string Link { get; set; }
        public bool CurrentYN { get; set; }
    
        public virtual LinksType LinksType { get; set; }
    }
}
