//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAdvisoryType
    {
        public MAdvisoryType()
        {
            this.ProductAdvisory = new HashSet<ProductAdvisory>();
        }
    
        public decimal AdvisoryType { get; set; }
        public string AdvisoryDescription { get; set; }
    
        public virtual ICollection<ProductAdvisory> ProductAdvisory { get; set; }
    }
}
