//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCAProp65
    {
        public decimal CAProp65ID { get; set; }
        public string Chemical { get; set; }
        public string CAProp65Text { get; set; }
        public string Notes { get; set; }
        public string Type { get; set; }
        public string CancerChemical { get; set; }
        public string DevelopmentalChemical { get; set; }
    }
}
