//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MContact
    {
        public MContact()
        {
            this.PressRelease = new HashSet<PressRelease>();
        }
    
        public decimal ContactID { get; set; }
        public Nullable<decimal> TerritoryID { get; set; }
        public Nullable<decimal> RegionID { get; set; }
        public string ContactTitle { get; set; }
        public string ContactLastName { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMobile { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual MRegion MRegion { get; set; }
        public virtual MTerritory MTerritory { get; set; }
        public virtual ICollection<PressRelease> PressRelease { get; set; }
    }
}
