//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLibrary
    {
        public MLibrary()
        {
            this.TechnicalLibrary = new HashSet<TechnicalLibrary>();
        }
    
        public decimal LibraryTypeID { get; set; }
        public string LibraryDescription { get; set; }
        public string LibraryMemo { get; set; }
    
        public virtual ICollection<TechnicalLibrary> TechnicalLibrary { get; set; }
    }
}
