//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNetTitle
    {
        public MNetTitle()
        {
            this.NetPriceInfo = new HashSet<NetPriceInfo>();
        }
    
        public decimal NetTitleID { get; set; }
        public string NetTitle { get; set; }
    
        public virtual ICollection<NetPriceInfo> NetPriceInfo { get; set; }
    }
}
