//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOtherRef2
    {
        public decimal OtherRef2ID { get; set; }
        public string OtherRef2Description { get; set; }
        public string OtherRef2Link { get; set; }
    }
}
