//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPageSection
    {
        public MPageSection()
        {
            this.NetPriceInfo = new HashSet<NetPriceInfo>();
            this.ProductPage = new HashSet<ProductPage>();
        }
    
        public decimal SectionID { get; set; }
        public string PageSection { get; set; }
    
        public virtual ICollection<NetPriceInfo> NetPriceInfo { get; set; }
        public virtual ICollection<ProductPage> ProductPage { get; set; }
    }
}
