//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPartUsage
    {
        public MPartUsage()
        {
            this.Webfields = new HashSet<Webfields>();
        }
    
        public decimal PartUsageID { get; set; }
        public string PartUsage { get; set; }
    
        public virtual ICollection<Webfields> Webfields { get; set; }
    }
}
