//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPPCIndustrySectionGroupPages
    {
        public int id { get; set; }
        public Nullable<decimal> MPPCInductryId { get; set; }
        public Nullable<decimal> MWebSectionId { get; set; }
        public Nullable<decimal> MWebGroupId { get; set; }
        public Nullable<decimal> PPCIndustryLink { get; set; }
        public Nullable<decimal> WebSectionSort { get; set; }
        public Nullable<decimal> WebGroupSort { get; set; }
    }
}
