//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPPCIndustry
    {
        public decimal PPCIndustry { get; set; }
        public string PPCIndustryName { get; set; }
        public string PPCIndustryNotes { get; set; }
        public string PPCIndustryImage { get; set; }
        public string PPCIndustryLink { get; set; }
        public Nullable<decimal> IndustrySort { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    }
}
