//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTerritory
    {
        public MTerritory()
        {
            this.MContact = new HashSet<MContact>();
            this.PressRelease = new HashSet<PressRelease>();
        }
    
        public decimal TerritoryID { get; set; }
        public string TerritoryName { get; set; }
    
        public virtual ICollection<MContact> MContact { get; set; }
        public virtual ICollection<PressRelease> PressRelease { get; set; }
    }
}
