//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWebGroup
    {
        public MWebGroup()
        {
            this.ProductPage = new HashSet<ProductPage>();
            this.TechnicalLibrary = new HashSet<TechnicalLibrary>();
        }
    
        public decimal WebGroupID { get; set; }
        public Nullable<decimal> WebGroupSort { get; set; }
        public string WebGroup { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    
        public virtual ICollection<ProductPage> ProductPage { get; set; }
        public virtual ICollection<TechnicalLibrary> TechnicalLibrary { get; set; }
    }
}
