//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWebSection
    {
        public MWebSection()
        {
            this.ProductPage = new HashSet<ProductPage>();
            this.TechnicalLibrary = new HashSet<TechnicalLibrary>();
        }
    
        public decimal WebSectionID { get; set; }
        public Nullable<decimal> WebSectionSort { get; set; }
        public string WebSection { get; set; }
        public string WebDescription { get; set; }
        public string WebOverview { get; set; }
        public string WebSectionAltTag { get; set; }
        public string WebSectionTitleTag { get; set; }
        public string WebSectionMemo { get; set; }
        public string WebSectionMetaTag { get; set; }
        public string WebSectionImage { get; set; }
        public string WebSectionLink { get; set; }
        public Nullable<bool> CurrentYN { get; set; }
        public string WebSectionIcon { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    
        public virtual ICollection<ProductPage> ProductPage { get; set; }
        public virtual ICollection<TechnicalLibrary> TechnicalLibrary { get; set; }
    }
}
