//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetPriceInfo
    {
        public string PartNo { get; set; }
        public string NetPriceDescription { get; set; }
        public Nullable<decimal> NetTitleID { get; set; }
        public Nullable<decimal> SectionID { get; set; }
        public Nullable<decimal> GroupID { get; set; }
        public Nullable<decimal> SORT1_Section { get; set; }
        public Nullable<decimal> SORT2_Group { get; set; }
        public Nullable<decimal> SORT3_Title { get; set; }
        public Nullable<decimal> SORT4_Part { get; set; }
        public Nullable<decimal> ProductPageCode { get; set; }
    
        public virtual MNetTitle MNetTitle { get; set; }
        public virtual MPageGroup MPageGroup { get; set; }
        public virtual MPageSection MPageSection { get; set; }
        public virtual ProductPage ProductPage { get; set; }
    }
}
