//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsWebfields
    {
        public string PartNo { get; set; }
        public string PartsPageCode { get; set; }
        public Nullable<decimal> Version { get; set; }
        public string DrawingNo { get; set; }
        public Nullable<decimal> Sort { get; set; }
        public Nullable<decimal> QProductID { get; set; }
        public string Barcode { get; set; }
    }
}
