//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsPage
    {
        public string PartsPC { get; set; }
        public string PageName { get; set; }
        public string BannerName { get; set; }
        public Nullable<double> WebSectionID { get; set; }
        public Nullable<double> WebGroupID { get; set; }
        public string imgTool { get; set; }
        public string ImgSchematic { get; set; }
        public string PDFSchematic { get; set; }
        public Nullable<double> PPC { get; set; }
        public Nullable<double> ManualID { get; set; }
        public Nullable<double> MaintenanceCardID { get; set; }
        public Nullable<double> PartsList { get; set; }
        public string OtherRef { get; set; }
        public string OtherRef1 { get; set; }
        public string OtherRef2 { get; set; }
        public string OtherRef3 { get; set; }
        public string ThumbNail { get; set; }
        public string AltPPC { get; set; }
    }
}
