//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsInfo
    {
        public string Partno { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public string Barcode { get; set; }
        public string PkgDimensions { get; set; }
        public Nullable<decimal> QProductID { get; set; }
        public Nullable<decimal> CAProp65ID { get; set; }
        public string CountryOrigin { get; set; }
        public string CommodityCode { get; set; }
        public Nullable<bool> CurrentYN { get; set; }
    }
}
