//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        public System.DateTime DatePosted { get; set; }
        public string PolicyHeader { get; set; }
        public string PolicySection { get; set; }
        public string Policy { get; set; }
    }
}
