//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressRelease
    {
        public decimal PressReleaseID { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public Nullable<System.DateTime> DateListed { get; set; }
        public string PRTitle { get; set; }
        public string PRDescription { get; set; }
        public string PRBlurb { get; set; }
        public string PRFooter { get; set; }
        public string PRImage { get; set; }
        public string PRLink { get; set; }
        public Nullable<decimal> TerritoryID { get; set; }
        public Nullable<decimal> RegionID { get; set; }
        public Nullable<decimal> ContactID { get; set; }
    
        public virtual MContact MContact { get; set; }
        public virtual MRegion MRegion { get; set; }
        public virtual MTerritory MTerritory { get; set; }
    }
}
