//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRelatedText
    {
        public decimal ProductPageCode { get; set; }
        public string RelatedText { get; set; }
        public Nullable<bool> Current { get; set; }
        public string PageName { get; set; }
    }
}
