//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBullets
    {
        public decimal ProductPageCode { get; set; }
        public Nullable<decimal> PBID { get; set; }
        public Nullable<decimal> PBOrderID { get; set; }
        public string PBText { get; set; }
        public string PBLinks { get; set; }
    }
}
