//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAdvisory
    {
        public decimal ProductAdvisoryID { get; set; }
        public decimal ProductPageCode { get; set; }
        public decimal AdvisoryType { get; set; }
        public Nullable<System.DateTime> DateListed { get; set; }
        public string AdvisoryTitle { get; set; }
        public string AdvisoryDescription { get; set; }
        public string AdvisoryImage { get; set; }
        public string AdvistoryLink { get; set; }
        public Nullable<bool> CurrentYN { get; set; }
    
        public virtual MAdvisoryType MAdvisoryType { get; set; }
        public virtual ProductPage ProductPage { get; set; }
    }
}
