//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPage
    {
        public ProductPage()
        {
            this.NetPriceInfo = new HashSet<NetPriceInfo>();
            this.ProductAdvisory = new HashSet<ProductAdvisory>();
            this.EducationalMaterial = new HashSet<EducationalMaterial>();
            this.NewProducts = new HashSet<NewProducts>();
            this.ProductVideo = new HashSet<ProductVideo>();
            this.TNTechNote = new HashSet<TNTechNote>();
            this.Webfields = new HashSet<Webfields>();
        }
    
        public decimal ProductPageCode { get; set; }
        public string PageName { get; set; }
        public string BannerName { get; set; }
        public Nullable<decimal> SectionID { get; set; }
        public Nullable<decimal> GroupID { get; set; }
        public Nullable<decimal> WebSectionID { get; set; }
        public Nullable<decimal> WebGroupID { get; set; }
        public Nullable<decimal> WebTitleID { get; set; }
        public Nullable<decimal> TechNoteID { get; set; }
        public Nullable<decimal> MSDSID { get; set; }
        public Nullable<decimal> ManualID { get; set; }
        public Nullable<decimal> MaintenanceCardID { get; set; }
        public Nullable<decimal> OtherReferenceID { get; set; }
        public Nullable<decimal> FlyerID { get; set; }
        public string DataSheet { get; set; }
        public string Thumb1 { get; set; }
        public string Thumb2 { get; set; }
        public string Thumb3 { get; set; }
        public string Thumb4 { get; set; }
        public string ThumbNail { get; set; }
        public string AdditionalItem { get; set; }
        public string Video1 { get; set; }
        public string SpecChart { get; set; }
        public string GritChart { get; set; }
        public string PictureLayout { get; set; }
        public string ChartLayout { get; set; }
        public string Thumb5 { get; set; }
        public string Thumb6 { get; set; }
        public string Thumb7 { get; set; }
        public string Thumb8 { get; set; }
        public string Thumb9 { get; set; }
        public Nullable<decimal> ProcessID { get; set; }
        public Nullable<decimal> OtherRef1 { get; set; }
        public Nullable<decimal> OtherRef2 { get; set; }
        public Nullable<decimal> OtherRef3 { get; set; }
        public Nullable<decimal> PartsList { get; set; }
        public string CatalogPageNo { get; set; }
        public string MetaTags { get; set; }
    
        public virtual MFlyer MFlyer { get; set; }
        public virtual MMaintenanceCard MMaintenanceCard { get; set; }
        public virtual MManual MManual { get; set; }
        public virtual MMsds MMsds { get; set; }
        public virtual MOtherReference MOtherReference { get; set; }
        public virtual MPageGroup MPageGroup { get; set; }
        public virtual MPageSection MPageSection { get; set; }
        public virtual MTechNote MTechNote { get; set; }
        public virtual MWebGroup MWebGroup { get; set; }
        public virtual MWebSection MWebSection { get; set; }
        public virtual MWebTitle MWebTitle { get; set; }
        public virtual ICollection<NetPriceInfo> NetPriceInfo { get; set; }
        public virtual ICollection<ProductAdvisory> ProductAdvisory { get; set; }
        public virtual ICollection<EducationalMaterial> EducationalMaterial { get; set; }
        public virtual ICollection<NewProducts> NewProducts { get; set; }
        public virtual ProductText ProductText { get; set; }
        public virtual ICollection<ProductVideo> ProductVideo { get; set; }
        public virtual ICollection<TNTechNote> TNTechNote { get; set; }
        public virtual ICollection<Webfields> Webfields { get; set; }
    }
}
