//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPage_Snippets
    {
        public decimal PPC { get; set; }
        public string SnipText1 { get; set; }
        public string Meta { get; set; }
        public string Keywords { get; set; }
    }
}
