//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestADealerInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postal { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string Mobile { get; set; }
        public string Promocode { get; set; }
        public string Profession { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CurDate { get; set; }
    }
}
