//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopIntlSpecUpload
    {
        public string part_number___522f29b472827380188d8806fe15260a { get; set; }
        public string spec_type__text__hidden__global_image__unique_image__file_ { get; set; }
        public string spec_name { get; set; }
        public string spec_description { get; set; }
        public string spec_file_name { get; set; }
    }
}
