//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopIntlCatDataTP
    {
        public string MFG_PART_NUMBER___af6ac23849fa72f624786667e0fc1b73 { get; set; }
        public string TOOLBAR_CATEGORY { get; set; }
        public string SUB_CATEGORY1 { get; set; }
        public string SUB_CATEGORY2 { get; set; }
        public string SUB_CATEGORY3 { get; set; }
        public string SUB_CATEGORY4 { get; set; }
        public Nullable<decimal> CATEGORYRANK { get; set; }
    }
}
