//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Description
    {
        public string PartNo { get; set; }
        public string Type1 { get; set; }
        public string Spec1 { get; set; }
        public string Detail1 { get; set; }
        public string Type2 { get; set; }
        public string Spec2 { get; set; }
        public string Detail2 { get; set; }
        public string Type3 { get; set; }
        public string Spec3 { get; set; }
        public string Detail3 { get; set; }
        public string Type4 { get; set; }
        public string Spec4 { get; set; }
        public string Detail4 { get; set; }
        public string Type5 { get; set; }
        public string Spec5 { get; set; }
        public string Detail5 { get; set; }
        public string Type6 { get; set; }
        public string Spec6 { get; set; }
        public string Detail6 { get; set; }
        public string Type7 { get; set; }
        public string Spec7 { get; set; }
        public string Detail7 { get; set; }
        public string Type8 { get; set; }
        public string Spec8 { get; set; }
        public string Detail8 { get; set; }
        public string Type9 { get; set; }
        public string Spec9 { get; set; }
        public string Detail9 { get; set; }
        public string Type10 { get; set; }
        public string Spec10 { get; set; }
        public string Detail10 { get; set; }
        public string Type11 { get; set; }
        public string Spec11 { get; set; }
        public string Detail11 { get; set; }
        public string Type12 { get; set; }
        public string Spec12 { get; set; }
        public string Detail12 { get; set; }
        public string Type13 { get; set; }
        public string Spec13 { get; set; }
        public string Detail13 { get; set; }
        public string Type14 { get; set; }
        public string Spec14 { get; set; }
        public string Detail14 { get; set; }
        public string Type15 { get; set; }
        public string Spec15 { get; set; }
        public string Detail15 { get; set; }
        public string Type16 { get; set; }
        public string Spec16 { get; set; }
        public string Detail16 { get; set; }
        public string Type17 { get; set; }
        public string Spec17 { get; set; }
        public string Detail17 { get; set; }
        public string Type18 { get; set; }
        public string Spec18 { get; set; }
        public string Detail18 { get; set; }
        public string Type19 { get; set; }
        public string Spec19 { get; set; }
        public string Detail19 { get; set; }
    }
}
