//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalLibrary
    {
        public decimal LibraryTypeID { get; set; }
        public decimal WebSectionID { get; set; }
        public Nullable<decimal> WebGroupID { get; set; }
        public Nullable<decimal> TechNoteID { get; set; }
        public Nullable<decimal> MSDSID { get; set; }
        public Nullable<decimal> ManualID { get; set; }
        public Nullable<decimal> MaintenanceCardID { get; set; }
        public Nullable<decimal> OtherReferenceID { get; set; }
        public Nullable<decimal> FlyerID { get; set; }
        public bool CurrentYN { get; set; }
        public Nullable<decimal> PartsListID { get; set; }
    
        public virtual MFlyer MFlyer { get; set; }
        public virtual MLibrary MLibrary { get; set; }
        public virtual MMaintenanceCard MMaintenanceCard { get; set; }
        public virtual MManual MManual { get; set; }
        public virtual MMsds MMsds { get; set; }
        public virtual MOtherReference MOtherReference { get; set; }
        public virtual MTechNote MTechNote { get; set; }
        public virtual MWebGroup MWebGroup { get; set; }
        public virtual MWebSection MWebSection { get; set; }
    }
}
