//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNTechNote
    {
        public decimal TNID { get; set; }
        public Nullable<decimal> ProductPageCode { get; set; }
        public Nullable<decimal> ProductPageOrderID { get; set; }
        public string TNBlurb { get; set; }
        public Nullable<decimal> TNHowID { get; set; }
        public Nullable<decimal> TNHelpID { get; set; }
        public Nullable<decimal> TNFAQID { get; set; }
        public string TNImage { get; set; }
        public string TNSpecChart { get; set; }
    
        public virtual ProductPage ProductPage { get; set; }
    }
}
