//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNTechNoteFAQ
    {
        public decimal TNID { get; set; }
        public Nullable<decimal> TNFAQID { get; set; }
        public Nullable<decimal> TNFAQOrderID { get; set; }
        public decimal ProductPageCode { get; set; }
        public string TNQText { get; set; }
        public string TNAText { get; set; }
        public string TNFAQImage { get; set; }
    }
}
