//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWWebfieldsUsageProcessApplication
    {
        public string PartNo { get; set; }
        public string PartUsage { get; set; }
        public string Process { get; set; }
        public string Application { get; set; }
    }
}
