//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWProductPageNoProductText
    {
        public decimal ProductPageCode { get; set; }
        public string PageName { get; set; }
        public string CatalogPageNo { get; set; }
        public Nullable<decimal> SectionID { get; set; }
        public Nullable<decimal> GroupID { get; set; }
        public string ShortDescription { get; set; }
        public string TechNote { get; set; }
        public string MSDS { get; set; }
        public string DataSheet { get; set; }
        public string Thumb1 { get; set; }
        public string Thumb2 { get; set; }
        public string Thumb3 { get; set; }
        public string Thumb4 { get; set; }
        public string ReferralItems { get; set; }
        public string Video1 { get; set; }
        public string Video2 { get; set; }
        public string PictureLayout { get; set; }
        public string ChartLayout { get; set; }
        public string LongDescription { get; set; }
    }
}
