//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphatoolServices.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webfields
    {
        public string PartNo { get; set; }
        public decimal ProductPageCode { get; set; }
        public Nullable<decimal> ApplicationID { get; set; }
        public Nullable<decimal> PartUsageID { get; set; }
        public Nullable<decimal> ProcessID { get; set; }
        public Nullable<decimal> SORT4_Part { get; set; }
        public string Weight { get; set; }
        public string ShopLink { get; set; }
        public string ShopImage { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> QProductID { get; set; }
        public bool CurrentYN { get; set; }
    
        public virtual MApplication MApplication { get; set; }
        public virtual MPartUsage MPartUsage { get; set; }
        public virtual MProcess MProcess { get; set; }
        public virtual ProductPage ProductPage { get; set; }
        public virtual WebPartNo WebPartNo { get; set; }
    }
}
